#Project_Euler_45.py
#Virata Yindeeyoungyeon
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n-1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def triangularPentagonalHexagonalNumber():
    #Hexagonal numbers are a subset of triangle numbers. Therefore, only need to find Hn=Pn
    pn = 165 + 1
    hn = 143

    while True:
        hVal = hn * (2 * hn - 1) 
        pVal = pn * (3 * pn - 1)/2

        if hVal > pVal:
            pn += 1

        if hVal < pVal:
            hn += 1

        if hVal == pVal:
            break

    return hVal

print(triangularPentagonalHexagonalNumber())
#1533776805

