#Project_Euler_2.py
#Virata Yindeeyoungyeon

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(index):
	if (index == 0):
		return 1
	elif (index == 1):
		return 2
	else:
		return fibonacci(index-2) + fibonacci(index-1)

def computeSumOfEvenNumber(upperLimit):
	index = 0
	sum_evenNumber = 0
	value = 0

	while (value < upperLimit):

		value = fibonacci(index)

		if (value % 2 == 0):
			sum_evenNumber += value

		index += 1

	return sum_evenNumber


print(computeSumOfEvenNumber(4000000)) #4613732
