//
//  main.m
//  Project_Euler_29
//
//  Created by Virata Yindeeyoungyeon on 3/12/16.
//  Copyright © 2016 Virata. All rights reserved.
//
/*
 Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 
 22=4, 23=8, 24=16, 25=32
 32=9, 33=27, 34=81, 35=243
 42=16, 43=64, 44=256, 45=1024
 52=25, 53=125, 54=625, 55=3125
 If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 
 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 
 How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */

#import <Foundation/Foundation.h>

int distinctPowers(int a, int b)
{
    NSMutableSet *set = [[NSMutableSet alloc] init];
    for (int i = 2; i <= a; i++) {
        for (int j = 2; j <= b; j++) {
            NSNumber *num = [NSNumber numberWithDouble:pow(i, j)];
            [set addObject:num];
        }
    }
    return (int)[set count];
}

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSLog(@"%i", distinctPowers(100, 100));
        //9183
    }
    return 0;
}
