//
//  main.m
//  Project_Euler_45
//
//  Created by Virata Yindeeyoungyeon on 4/28/16.
//  Copyright © 2016 Virata. All rights reserved.
//
/*
 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 
 Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
 Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 It can be verified that T285 = P165 = H143 = 40755.
 
 Find the next triangle number that is also pentagonal and hexagonal.
 */

#import <Foundation/Foundation.h>

long triangularPentagonalHexagonalNumber()
{
    //Hexagonal numbers are a subset of triangle numbers. Therefore, only need to find Hn=Pn
    long pn = 165 + 1;
    long hn = 143;
    long returnVal = 40755;
    
    while (YES) {
        long pVal = pn * (3 * pn - 1)/2;
        long hVal = hn * (2 * hn - 1);
        
        if (pVal < hVal) {
            pn += 1;
        } else if (pVal > hVal) {
            hn += 1;
        } else {
            //pVal == hVal
            returnVal = hVal;
            break;
        }
    }
    
    return returnVal;
}

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSLog(@"%li", triangularPentagonalHexagonalNumber());
        //1533776805
    }
    return 0;
}
